version: '3.1'

services:

  mongo:
    image: mongo:latest
    restart: always
    ports:
    - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_DATABASE: chat
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    volumes:
      - ./volumes/mongo:/data/db

  server:
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      MONGO_INITDB_ROOT_DATABASE: chat
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    depends_on:
      - mongo

  client:
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - server
